[tool.poetry]
name = "network-live"
version = "0.1.0"
description = "Collects all cells for all technologies for the Kcell radio network"
authors = ["Ramil Albakov <ramil.albakov2@gmail.com>"]
readme = "README.md"
packages = [{include = "network_live"}]

[tool.poetry.dependencies]
python = "^3.8"
python-dotenv = "^1.0.0"
enm-client-scripting = {path = "../local_packages/enm_client_scripting-1.22.2-py2.py3-none-any.whl"}

[tool.poetry.scripts]
update-enm1-lte = "network_live.scripts.update_enm_lte:main_enm1"
update-enm2-lte = "network_live.scripts.update_enm_lte:main_enm2"

[tool.poetry.group.dev.dependencies]
wemake-python-styleguide = "^0.17.0"
pytest = "^7.3.0"
pytest-cov = "^4.0.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
